### ISSUE TITLE
not save the size of the width of the feed column after closing the browser

### ISSUE THREAD

**Issue by rubel-22** [zakius/Smart-RSS#102]
The latest version of smart_rss_reader-2.12.1 works very well, but does not save the size of the width of the feed column after closing the browser. How to remove items from All channels and Pinned in the screenshot?
[url=https://i111.fastpic.ru/big/2020/0318/ee/281ec61a9a34542ef8f4dd9987d201ee.png][img]https://i111.fastpic.ru/big/2020/0318/74/51ac2115af141c224bd30bec65499b74.png[/img][/url]

**Comment by zakius** [comment]
If you want to hide these special groups it's not possible now, if you want to remove items grouped under them you can do it normally but be aware these are not copied there so it affects the actual feed

As for not saving the width, I'll look into it
