### ISSUE TITLE
DeviantArt - Images aren't shown in the preview pane

### ISSUE THREAD

**Issue by AtTheGates** [zakius/Smart-RSS#103]
Hello,

I realized, that preview images of **DeviantArt** in the preview pane of the extension aren't shown, like the old **NewsFox** does.

For example: I use this feed address: **https://backend.deviantart.com/rss.xml?q=+sort%3Atime+in%3Acustomization%2Fskins%2Fwindows%2Fwin10&type=deviation**

In **NewsFox** v1.0.9.4.1 (Windows 10, FF ESR v52.9.0) it looks like this:

![newsfox_previewpane](https://user-images.githubusercontent.com/9346225/77183370-837c7380-6ace-11ea-886b-5495c0a18d7a.png)

Shown image is from this feed entry: **https://www.deviantart.com/cleodesktop/art/Mino-Dark-Blue-And-Red-Theme-Windows10-1909-834472404**

With your wonderful extension v2.12.1 (Windows 10, FF v74.0) no images are shown.

Thank you in advance. :-)

**Comment by zakius** [comment]
Okay, that's bizarre, when you subscribe to someone's feed it works as intended but they serve you a proper RSS 2.0 document with and `<img>` tag in the contents

but your link provides something else, I'm not even sure what it exactly is, thankfully the way this extension parses feeds makes it possible to parse any valid XML that resembles a feed, but I still have to do some research

**Comment by zakius** [comment]
Loading the image link was pretty simple, but to fully support it I have to rebuild my `enclosure` handling code and alter interface too (references #90), it'll likely take some time

**Comment by AtTheGates** [comment]
Thank you very much. Just take your time. It isn't really important for me atm. I just thought, I report it. :-)

**Comment by zakius** [comment]
solved as stated in #90
