### ISSUE TITLE
Search in extension does not work correctly.

### ISSUE THREAD

**Issue by rubel-22** [zakius/Smart-RSS#105]
Search in extension does not work correctly.
How to find the right word in the news?
Please explain in more detail.
Thanks.

**Comment by zakius** [comment]
What do you mean by "doesn't work correctly"? By default it searches in titles only, to perform search in contents too (only these available in feed of course) you should start your query with `:` IIRC, personally I'm not using search at all so I'm not sure right now, but there should be a tooltip stating it

**Comment by zakius** [comment]
Just tested it and can't see any issues

**Comment by zakius** [comment]
okay, I see it doesn't work on `All items`, will look into this

**Comment by zakius** [comment]
While at this I found issue with folder handling, both should be fixed in Master now
