### ISSUE TITLE
Restore putting unread at top in All Feeds

### ISSUE THREAD

**Issue by asorel1942** [zakius/Smart-RSS#108]
In previous iterations of this plug-in (using Firefox on Linux), the All Feeds section would show unread articles only. The advantage of this was that an unread article was put towards the top of the screen, and was easily accessible even if quite old. Now that All Feeds shows both unread and read articles, unread articles aren't as easily accessible. Would it be possible to set All Feeds to automatically list unread items before read items once again, or enable an option for this feature?

**Comment by zakius** [comment]
clicking on the unread counter or with `alt` key depressed shows unread only for any source on the list, there was no special treatment for `All feeds`
