### ISSUE TITLE
Add easier feed management

### ISSUE THREAD

**Issue by zakius** [zakius/Smart-RSS#13]
- [x] i.e. moving sources between *folders*
    - [ ] moving multiple sources at the same time
- [ ] make *folder* nesting possible

**Comment by atomGit** [comment]
ability to drag & drop folders, or reorder them in some other way would be good too

re: nesting folders - i haven't seen that in any other FF reader and i'm not sure how necessary that is, but that's just my opinion

**Comment by samthelion** [comment]
> 
> 
> ability to drag & drop folders, or reorder them in some other way would be good too
> 
> re: nesting folders - i haven't seen that in any other FF reader and i'm not sure how necessary that is, but that's just my opinion

Brief (firefox addon) has those capabilities, but SmartRSS looks better and is faster :(
i don't know wich one to choose

**Comment by zakius** [comment]
drag and drop is useful but gets messy with long lists, I'll look into it when I have some time
nesting may be useful and doesn't seem too complicated

@samthelion I picked up this project mostly because it was the easiest way of dealing with pain points in other readers, Newsfox was pretty much perfect but slow and not supported by quantumfox
as I resolved most of my personal issues development slowed down a lot, but I hope to get back to it sooner than later

**Comment by atomGit** [comment]
actually i'm going to revoke my request for this feature

i've gotten used to having the 'folders' in alphabetical order

**Comment by zakius** [comment]
won't work on nesting, at least not in foreseeable future
