### ISSUE TITLE
Polish main view

### ISSUE THREAD

**Issue by zakius** [zakius/Smart-RSS#16]
There are some issues with main view, notably:

- [x] it sometimes gets too wide causing horizontal scrollbar to appear
- [x] there are scaling issues when using `layout.css.devPixelsPerPx` or changing font size in options
- [x] sources list items have variable height depending on badge existence

while I can reproduce first two problems I still can't figure out the reason

**Comment by zakius** [comment]
currently font size up to 150% and `layout.css.devPixelsPerPx` up to 1.5 seem to behave properly, setting `layout.css.devPixelsPerPx` to 2.0 still breaks (but there's not enough place to fit the layout any way so I think such high values can't be supported)

**Comment by Konrad008** [comment]
#18 fix for 1st item list

**Comment by zakius** [comment]
for future reference: Flexbox' min-height and min-width by default equals to the size of content, to allow it to shrink properly these properties have to be overridden
