### ISSUE TITLE
Prepare promotional images for Chrome store

### ISSUE THREAD

**Issue by zakius** [zakius/Smart-RSS#24]

**Comment by Fraasi** [comment]
I took a quick look at what they require. Here's googles guidelines on the subject
https://developer.chrome.com/webstore/images?hl=en#promo  
Any guidelines/thoughts on what this should look like @zakius?

**Comment by zakius** [comment]
Unfortunately I have no idea what to do about this, I don't have any brand to promote or literally anything that would make sense on promo images, tools like this aren't really fashionable either way

Possibly some combination of icon and name would do, it just has to be there for the automated part of submission system to pass package further in approval chain

Now that I think about it it will be required to prepare something for Detector too
