### ISSUE TITLE
Context menu of Smart-RSS is covered

### ISSUE THREAD

**Issue by gabri25ele** [zakius/Smart-RSS#49]
the context menu (right button) of Smart-RSS is covered by the context menu of firefox:

![sshot-1](https://user-images.githubusercontent.com/33927879/55864432-c888ed80-5b7c-11e9-80fd-245dc9818f68.png)

does not happen with previous versions of the extension, for example I reinstall 2.0.16 (all ok with this version)

**Comment by zakius** [comment]
Release fixing this issue should be available in few hours, it's fixed in Master already
