### ISSUE TITLE
Add theme & custom style support

### ISSUE THREAD

**Issue by Crystal-RainSlide** [zakius/Smart-RSS#60]
You may put this after https://github.com/zakius/Smart-RSS/issues/19 so users will suffer less from the changing of default style.

And here's some style for test:
```
.toolbar { background: var(--grey-20); }
.date-group { background: var(--grey-10); }
```

**Comment by zakius** [comment]
Custom theme support definitely has to come after cleaning up the default styling, it's also possible that some extra variables will be required to make theming simple (just overriding variables), but of course injecting completely new stylesheet will also be possible if someone wishes to do it. Unfortunately I cannot predict when I'll be able to get to this task

**Comment by atomGit** [comment]
@Crystal-RainSlide - here's a dark theme i quickly hacked together if it help you: #65

**Comment by Crystal-RainSlide** [comment]
@atomGit Thanks! It helps a lot.

**Comment by zakius** [comment]
I still intend to do #19 but this one was low hanging fruit so I decided to do it first for people who really need it
