### ISSUE TITLE
fails to import directory structure (OPML import)

### ISSUE THREAD

**Issue by atomGit** [zakius/Smart-RSS#64]
it appears the 'outline title' tag is ignored - other readers import this ok, but SmartRSS doesn't - in the sample below, the 'News, General' folder is never created

partial sample of opml file...

```
<?xml version="1.0" encoding="UTF-8"?>
<opml version="1.0">
<head>
<title>Feed Subscriptions</title>
</head>
<body>
  <outline title="News, General" text="News, General">
      <outline text="21st Century Wire" title="21st Century Wire" type="rss" 
            xmlUrl="http://21stcenturywire.com/feed/" htmlUrl="https://21stcenturywire.com"/>
```

**Comment by zakius** [comment]
This is a display issue, reloading reader view causes missing directories to appear. Looks like Sources tree is not rerendered properly on Folders collection change, I'll look into this

**Comment by atomGit** [comment]
ah, and here i kept dumping the data and re-importing without thinking to simply refresh :)

thanks
