### ISSUE TITLE
replace author name with feed source in headline list?

### ISSUE THREAD

**Issue by atomGit** [zakius/Smart-RSS#66]
if you have feeds organized in folders and click a folder to display all feeds in that folder, in the headlines list (center pane) the author name of the article is displayed for all items instead of the feed source - only if you click an individual feed is the source is displayed and, in my case, i never do that because i have too many feeds to click through them all

the author name is already displayed in the article pane, so i think the site title should always be displayed in the headlines pane - personally, when i scan headlines, i want to first see where the article came from, not who wrote it, but when i click an article, then i want to see the author - the way it is now, you never know where an article came from unless you click the feed item in the left-most pane

another thing that would help would be to insert the feed source icon (favicon) next to the headlines in the headline list

**Comment by zakius** [comment]
huh, I'm not sure if I changed this without updating the issue or if I don't understand what you want to achieve, but can you check if it's like you wanted it?

please note that the favicon part is surely unchanged

**Comment by atomGit** [comment]
hi zakius - no, this wasn't changed

in the center/headline pane, the author name of the article is displayed and this is repeated again in the article pane - the site name is never displayed

what i'm suggesting is that the center/headline pane display the site instead of the author - example:

site: 21st Century News
article title: How to catch a chicken
author: Stumpy

so in the headline pane:

How to catch a chicken
21st Century News

in the article pane:

How to catch a chicken
Stumpy

**Comment by zakius** [comment]
Okay, this is weird, I'm sure that all code up to yesterday is released but master branch running in Waterfox 68 Alpha behaves exactly like you suggest while latest release running in latest 56 doesn't, I'm going to look into this as I expect some typecasting error

**Comment by atomGit** [comment]
if it helps, i'm running Firefox 67.0.3 and Smart RSS 2.1.1 which is the latest that Firefox knows about (i just checked for updates)

**Comment by zakius** [comment]
Okay, I got this

Author defaults to source name if author is not defined at all and it just so happens a lot of my sources don't define author fields causing some confusion.

Actually implementing this will take me some time and I may take some shortcuts (like displaying both source title and author always)

**Comment by atomGit** [comment]
sounds fine to me - the most important thing for me is to know the source of the article in the headline column/pane - if the author is included, that's a bonus and if it's easier to include both, please do

**Comment by zakius** [comment]
added in latest version

**Comment by atomGit** [comment]
thanks! this is something i've been looking forward to
