### ISSUE TITLE
option to show only unread

### ISSUE THREAD

**Issue by atomGit** [zakius/Smart-RSS#67]
the sorting options are very useful, but i'd like to propose adding an 'unread' filter to both options, or perhaps better yet, adding a button on the toolbar that toggles between displaying all articles and displaying unread only

**Comment by zakius** [comment]
There's one special thing about SmartRSS: it additionally has the state called New, so you can click on article, quickly glance over it so it isn't *new* anymore but stays unread. Of course you can tuen on auto marking as read too.

I'll probably just add filters for both Unread and New only

**Comment by atomGit** [comment]
hi zakius - the issue i'm looking to solve is unread articles being interspersed among read articles - unless there's something i'm not understanding, i don't think the 'New' state solves that???

why unread stuff sometimes gets mixed with read, i don't know - perhaps there's missing date info in the feed or something

**Comment by zakius** [comment]
The bold blue titles are new, bold ones are unread. I'm not sure what is your exact issue as to be honest I just remove articles that I'm not longer interested in so I have no *read* ones at all, but I'll try changing my habit for a few days to look further into in. In the meantime can you elaborate a bit more? So I'll know what to look at exactly. Maybe you're experiencing articles updating, it is intended to let you know something changed, though possibly I could use a new state for that in the future to avoid confusion

**Comment by atomGit** [comment]
> The bold blue titles are new, bold ones are unread.

yes, i'm aware of that, the problem is that there may be 10 unread articles, then 3 read ones, then 1 unread, repeat... i don't think all of the read ones that are located in the list between unread are updated articles, however i may be wrong

if you intend to auto-purge read articles, or add a sorting option to sort by unread (this would work great as a last sort option), i think that would work great

**Comment by zakius** [comment]
I'll add the mentioned filters and consider auto removal

I'm not sure about sorting, I assume it would show reverse chronologically unread items first and then read ones?

And to clarify things: are you experiencing and submitting a bug report or only suggesting enhancement?

**Comment by atomGit** [comment]
> I'm not sure about sorting, I assume it would show reverse chronologically unread items first and then read ones?

that's what i had in mind

> are you experiencing and submitting a bug report or only suggesting enhancement?

feature :)

**Comment by zakius** [comment]
Okay, I get it

Currently I have one version to release and few bugs to take a look at, but I'll get to your requests in some time

**Comment by atomGit** [comment]
that's great - no hurry - and sorry for all the issues i've been submitting - i've kinda been pretty frustrated trying to find a good feed reader since Newsfox died as a result of the WebExt API and i think yours is the best candidate :)

**Comment by atomGit** [comment]
i'm going to rescind this feature request as well
