### ISSUE TITLE
address bar icon color

### ISSUE THREAD

**Issue by atomGit** [zakius/Smart-RSS#68]
i didn't know S-RSS did feed detection - nice! however the icon it adds to the address bar is next to invisible when using the default dark FF theme

**Comment by zakius** [comment]
I have to figure out a lot of things according theming, I don't think there's any color that would work well in all themes and I don't see a reliable way of detecting theme yet. As a quick workaround I'll probably add ability to change this icon in settings

**Comment by atomGit** [comment]
> I'll probably add ability to change this icon in settings

that's how a lot of dev's seem to handle it - they'll just have an option to manually change the icon

**Comment by zakius** [comment]
Closing this as detector `PageAction` will be reworked to become context menu of `BrowserAction` to increase consistency of UI and help muscle memory (`PageActions` show and hide making it impossible to precisely aim for them) + reduce packaging complexity across browsers (Chromium Extensions can't use both `PageAction` and `BrowserAction` in the same extension)
