### ISSUE TITLE
leekwire.com feed issue

### ISSUE THREAD

**Issue by atomGit** [zakius/Smart-RSS#73]
article links for https://leekwire.com/v//feed are getting messed up - i think this might be a feed format issue, but previous feed reader didn't cause this

here's an example...

```
<image>
<title>RSS LEEKWire - Uncensored Video Host</title>
<url>https://leekwire.com/v/videos/userPhoto/logo.png</url>
<link>https://leekwire.com/v/</link>
<width>144</width>
<height>40</height>
<description>YouPHPTube versione rss</description>
</image>

    <item>
<title>STRATEGY of TENSION (2019) Full Documentary</title>
<description>blah blah</description>
<link> https://leekwire.com/v/v/5550</link>
<pubDate>Sat, 18 May 2019 02:31:54 -0400</pubDate>
<guid>https://leekwire.com/v/v/5550</guid>
    </item>
```

that `<image>` block is supposed to be inside the `<item>` block, no?

the S-RSS link for the article ends up as...
`https://leekwire.com/%20https://leekwire.com/v/v/5550`

**Comment by zakius** [comment]
AFAIK that Image tag fits there properly and old Firefox' feed preview displays it next to the feed title so I assume this part is right

As I can see these links contain space as a first character for some reason, trimming them should do it. While I'm at it I'll trim every field to be sure nothing else breaks, though in most cases it would only cause display issues
