### ISSUE TITLE
update interval for added feeds should default to global default

### ISSUE THREAD

**Issue by atomGit** [zakius/Smart-RSS#74]
when adding a feed, i noticed the update interval was set to 3 hrs (despite 'Default update frequency' being set to 15 min) - in my case 'Disable auto update completely' is enabled, so i think it would be expected that the same would be the default when adding a feed

**Comment by zakius** [comment]
I'll take a look at it once again, probably it should be configurable too since some feeds define their TTL themselves so you should be able to either use their TTL (or the closest bigger setting available), overwrite always or overwrite only longer (to not put too much strain on the server)
