### ISSUE TITLE
Stopped working after browser refresh

### ISSUE THREAD

**Issue by 0450** [zakius/Smart-RSS#80]
Smart-RSS was working fine and I really liked it, but after I accidentally refreshed Firefox and reinstalled my Add-ons, Smart-RSS stopped working. All the other add-ons works just fine.

On the taskbar, the Smart-RSS icon is stucked on the loading animation. When I click the icon, either nothing happens or it just pops out a small empty window. The latter happens after I clicked around to other tabs a few times. 
![yesterday](https://user-images.githubusercontent.com/51217597/61592370-fc36d300-abc1-11e9-944d-8fcc75044263.png)

I tried going to a site and opening the reader through the option "Choose RSS feed to copy URL:" on the navigation bar icon. It did open up the reader but it was blank with a couple of lines.
![today](https://user-images.githubusercontent.com/51217597/61592434-ae6e9a80-abc2-11e9-9eb7-625c80dd4f90.png)

- Tried creating a new Firefox profile and installing the add-on and it indeed worked. So I copied the files from the new profile\extensions\smart-rss@ mozilla.firefox.xpi and new profile\storage\default\moz-extension+++(wtv the extension's link was)^firstPartyDomain=(wtv the extension's link was) to my orginal profile but that didn't work.

- Tried migrating to the new profile by moving my all files from the original profile to the new one but there were too many problems with doing that and I'm too tired to re-configure everything again and again (not the first time i accidentally refreshed Firefox).

- Tried disabling all the add-ons and only enabling Smart-RSS, that didn't work too.

- Tried creating a new profile and launching Firefox with my user.js (altered ghacks user.js) from the original profile to install the add-on. The same problem was happening on it. I thought it might have been a conflict with a setting i added or changed in the user.js file that caused the problem (was also using an altered ghacks user.js file before this refresh), so I removed the user.js and generated a clean ghacks user.js file through their updater.bat and cleaning the pref.js through prefsCleaner.bat. Re-installed Smart-RSS and it still didn't work.
[user.txt](https://github.com/zakius/Smart-RSS/files/3414727/user.txt)

- Tried out installing another RSS reader and it worked fine.

Sorry being long-winded but I have no idea left on what is causing this problem.

**Comment by zakius** [comment]
looks like another issue with first party isolation, as I'm not sure what exactly happens when you refresh your profile I don't know what is the state of your data

do you have your extension data backed up anywhere or existing in that old profile? if so you can try restoring them by following these steps:

- create new profile
- install extension on new profile (that should create new storage directory for this extension)
- copy contents of old extension storage into the new directory
- launch FF with that new profile
- if it loads properly use SMART export function in settings and close browser
- remove extension storage directory from browser profile you want to use (or better back it up for safety)
- launch FF with old profile
- import the file you just created

**Comment by 0450** [comment]
I did have the extension data backed up but i do not know which was the number to the sea of moz-extension+++s. I still tried doing the method u suggested without the old data and ended up with an error importing the file. 
![2019 07 22 - 14 19 44 firefox](https://user-images.githubusercontent.com/51217597/61613218-4936aa00-ac93-11e9-8632-84d10a15adbe.png)
![2019 07 22 - 14 29 35 firefox](https://user-images.githubusercontent.com/51217597/61613226-518ee500-ac93-11e9-87fa-5e98de8972fc.png)

**Comment by 0450** [comment]
I ended up moving my profile to the another one and so far everything is looking good and Smart-RSS is working again :D
