### ISSUE TITLE
Media content tags are not recognized

### ISSUE THREAD

**Issue by MostAwesomeDude** [zakius/Smart-RSS#81]
Hi! I have some feeds with media file URLs embedded. https://allthepresidentslawyers-feed.kcrw.com/ is an example feed. Right now, I have to go over to a second RSS extension in order to quickly retrieve those URLs, or view the source of the RSS feed, or similar. It would be great if the media URLs were listed in Smart RSS.

**Comment by zakius** [comment]
Hello, I don't think I've used feeds like this, can you explain how would it look like or tell me which extension does that and I'll figure it out?

**Comment by MostAwesomeDude** [comment]
Yes, there are usually URLs for MP3s attached to these feeds. https://www.espn.com/espnradio/feeds/rss/podcast.xml?id=14554755 is another example of such a feed.

As far as user stories, I am extremely boring; I right-click the MP3 URL, copy it to my clipboard, and paste it in a custom-made media player application. I don't need anything aside from the URL.

The extension I'm currently using for this is "Feed Preview" https://code.guido-berhoerster.org/addons/firefox-addons/feed-preview/

Thank you for your consideration and hard work.

**Comment by zakius** [comment]
Okay, I'll look into it and it should be available in next release, but I can't give you ETA

**Comment by MostAwesomeDude** [comment]
No worries. My current workflow is fine; this will merely be a quality-of-life improvement. Thank you.

**Comment by zakius** [comment]
due to various reasons I was unable to work on this all this time, I'll be pushing long due bugfix for another issue first before reevaluating backlog and reassigning priorities, sorry

**Comment by zakius** [comment]
I'm starting to work on it, it will be really basic and rough around the edges first (no type icons, probably just displaying MIME type, interface may be little sketchy) but once I get that working it can only get better

**Comment by zakius** [comment]
I just pushed initial version (should be available to download from AMO in few hours or from GitHub unsigned right now) that you may test against feeds you use daily, as mentioned earlier visually it's not so pleasant but gets the job done

@MostAwesomeDude

**Comment by MostAwesomeDude** [comment]
I'm happy to report that the feature works as advertised. Like you say, it is very basic, but it provides everything I need. Thank you very much.

**Comment by zakius** [comment]
I'm glad feature-wise it's what you needed, I'll close this one and open new to specifically address styling
