### ISSUE TITLE
[feature] option to disable headline tool-tips and display full headline

### ISSUE THREAD

**Issue by atomGit** [zakius/Smart-RSS#85]
in the style sheet i use ( #65 ), i changed the CSS to display the full headline - personally i think the headline is most important and so i see no reason to trim it, however after making this change, the headline tool-tips are unnecessary - if these can be hidden via CSS, please let me know (i'd need the selector), else please consider adding an option to disable them

**Comment by zakius** [comment]
just pushed update implementing this to AMO

**Comment by atomGit** [comment]
thank @zakius - i'm happy to see you're still working on this code

far as i'm concerned, you've built the best RSS reader for Firefox and i've likely tested every one :)

**Comment by zakius** [comment]
thanks for your kind words, but don't forget I'm building on solid foundation created by martinkadlec0
without his work I probably would never leave NewsFox behind :D
