### ISSUE TITLE
Options - Layout: Doesn't save the chosen state

### ISSUE THREAD

**Issue by AtTheGates** [zakius/Smart-RSS#86]
Hello,

first thank you very much for your extension. I'm coming from the good old "NewsFox". For me your extension is the best alternative for Quantum. 👍 

To the problem: If I choose in "Options" under "Appearance -Layout" the second mode, it get always resetet to the first (default) mode, if I close the tab or restart Firefox. Another problem: If I move the splitters (left/ right) the state isn't also saved.

Tested on:

- Windows 10 64bit
- Firefox v71.0
- New fresh profile without any other extensions or modifications

Thank you in advance to take a look into this.

**Comment by zakius** [comment]
I can confirm that layout and size of first pane doesn't save, I will look into this but can't give you any ETA

**Comment by zakius** [comment]
I'll probably release new version with this and other fixes in a few days

**Comment by AtTheGates** [comment]
Wow... thank you very much. :-)

**Comment by zakius** [comment]
just pushed update fixing this to AMO
