### ISSUE TITLE
Bookmarks backend

### ISSUE THREAD

**Issue by dyeray** [zakius/Smart-RSS#87]
Feature suggestion: Store feeds and read status using bookmarks. This would make it work on Tor Browser (I think addons that use IndexedDB don't work right now) and also get support for synchronizing multiple Firefox installations for free (using firefox sync).

**Comment by zakius** [comment]
While it may be possible to store sources structure this way and possibly even list of articles I don't think it is possible to properly mark articles as read, remove them in a way that prevents them from reappearing if they are still present in feed file and especially to store their contents.

If you know any extension that achieves that it would be really helpful, if not I'll look into it, but I can't promise anything

**Comment by dyeray** [comment]
I think you are right. Exclusively using bookmarks may be unfeasible. I had thought about an approach like this for a feed reader for a long time, but just to sync what articles are read or not. The idea of completely replacing IndexedDB came to my mind just after realizing that RSS readers don't seem to work on Tor Browser.

But anyways, setting that aside, supposing we just want to sync what feeds we have added and what articles were already read then it's maybe feasible. I was thinking that each feed can have a bookmark with serialized metadata on the url field. Something like a list of read articles plus a minimum date (any article older than that date should also be considered read). Probably would be a bit tricky on some cases though (feeds without date of publishing, updated articles, etc.).

**Comment by zakius** [comment]
I wish I could provide easy sync but I see no way of leveraging existing mechanisms for it, I'm sorry
