### ISSUE TITLE
Don't Select/mark as read articles when navigating the app.

### ISSUE THREAD

**Issue by dyeray** [zakius/Smart-RSS#88]
When using the option to mark as read when selecting articles there are a couple of usability issues:

* When the extension is opened by default the "All feeds" section is selected, which marks the newest unread article as read invariably.
* When trying to open a folder to read the articles of a specific feed, 2 clicks are needed. The first one selects the folder, and marks as read the newest article of this folder (something the usually probably does not intend to do). The second click opens the folder, so a single website can be selected.

**Comment by ingvar-lynn** [comment]
I would expect this enhancement greatly as i find this aforementioned behaviou as the only downside of this extension.

**Comment by zakius** [comment]
just pushed update implementing this optionally to AMO
