### ISSUE TITLE
Import in "smart" format doesn't work.

### ISSUE THREAD

**Issue by Lichtenshtein** [zakius/Smart-RSS#89]
Trying to import my database from https://chrome.google.com/webstore/detail/rss-агрегатор/mfnlknjiipcimlomahgahebhljlajfeg (another Smart RSS fork), but getting an error while import:

`Importing error: Uncaught TypeError: Cannot read property 'transaction' of undefined`

I found a few "transaction" words in DB, deleting them didn't help. Database itself is 90mb, lots of saved and unread articles :\

Any tips?

**Comment by zakius** [comment]
I'll take a look at it probably this weekend
What are your browser and extension version?

**Comment by Lichtenshtein** [comment]
Thank you!
Cent Browser 4.1.7.182 (32 bit) Chromium 78.0.3904.108
Chromium 2.0.33

**Comment by zakius** [comment]
that's pretty old build, if you are able to build yourself (instructions in readme) please do it from latest commit, if not I'll try to upload latest one to GitHub today

later I'll try resubmitting to Chrome Web Store, but this may not go as smoothly

**Comment by zakius** [comment]
I just published updated package on GitHub and pushed it to CWS, though verification there can take even few weeks according to their messages

If I remember correctly you should be able to install extensions from outside the store on Cent Browser without issues but I'm not sure if it will work properly after all the changes in permissions in last months, I may need to rebuild Chromium manifest again

**Comment by Lichtenshtein** [comment]
SmartRSS v2.3.0 chromium
Looks like options.js on options page is not loading correctly, all options are inactive and are reseted after page reload. Tested on Cent and SRWare Iron 79.0.4100.0. Firefox version from the store works correctly (but lags as hell (27k articles) when i open the rss window).

**Comment by zakius** [comment]
thanks for the feedback, seems I'll have to grab Chromium as Chredge doesn't even load manifest properly...

will see what I can do, tbh I was considering dropping chromium support altogether as both CWS and Chropera repo are annoying to work with and constant permission shuffles make it a pain but I'll try

**Comment by Lichtenshtein** [comment]
Been experimented a bit. I've deleted lines 39-42 in options.js and options page loaded correctly
```
        if (!browser) {
            const warning = document.querySelector('.ff-warning');
            warning.parentNode.removeChild(warning);
        }
```
Deleted 303-315 and 327 lines and succesfully imported the .smart file. If i didn't do this import just stops on "loading & parsing file" message and doesn't work.

All because of "browser is not defined" errors, after all this message still persists in the console... 

It seems that this fork does not work well with a large amount of news articles... as soon as I open the rss window, it becomes inaccessible for a minute or more (I can scroll the left panel, but I can’t click anything) and the browser asks to close the page, considering it to be frozen. Also news icons are not loading, not sure why...

**Comment by zakius** [comment]
seems chromium changed a bit, before it worked fine while used like that, will change to explicitly check if browser is defined

for me performance isn't any issue, I have huge backlog myself and it just works

are all your issues happening in chromium? I'll experiment a bit to see if anything can be done easily

**Comment by zakius** [comment]
Okay, I fixed manifest, import and few other things (disabled prefetcher) for chromium

performance wise it is pretty slow for up to few minutes after import (as it tries to update all feeds) and slow-ish during data fetching (as it may use multiple connections, it's configurable), but once everything is loaded it works fine with my >7k backlog on Waterfox Classic (so pretty outdated in terms of performance)

I uploaded updated chromium package to GitHub

I hope the import issue is resolved properly, if you have any other problems please open a new issue and we'll work through it there

**Comment by Lichtenshtein** [comment]
Yes, the import issue is fixed :)

> performance wise it is pretty slow for up to few minutes after import (as it tries to update all feeds) and slow-ish during data fetching (as it may use multiple connections, it's configurable), but once everything is loaded it works fine with my >7k backlog on Waterfox Classic (so pretty outdated in terms of performance)

Does it like loads 7k micro web pages at once? Because i noticed that the memory consumption of the extension is quite large for the extension, almost like the browser itself...

![134](https://user-images.githubusercontent.com/13855295/74664656-08096880-5196-11ea-82f7-3758da7a307b.png)

**Comment by zakius** [comment]
>Does it like loads 7k micro web pages at once?

Whole collection is handled in memory and only mirrored to IndexedDB so one can say that.

FFDev shows reasonable numbers, but is inconsistent
Chromium variant seems to handle it differently and it grows to over 120 just on load and opening the view doubles that (and that is pretty consistent with OG extension as I just checked). 

I have no idea how to approach that and I don't think I'll target this issue specifically, though fixing #72 may affect this. 
Unfortunately it's a big task that I'm pushing away to focus on low hanging fruit earlier as for my personal needs the workaround works good enough

**Comment by zakius** [comment]
I just uploaded updated packages to GitHub, still trying to get through CWS validation and can't guarantee it will succeed
closing this now as the main issue is resolved

**Comment by Lichtenshtein** [comment]
SmartRSS v2.4.0 chromium
Import in ".smart" is broken again for me. It says that the import was successful, but not a single feed, folder appears. Disk space is consumed as if the file was really imported.

**Comment by zakius** [comment]
I just tried it in chredge as I don't have any other chromium on this machine and it worked just fine, but I'll try few more things and maybe I'll be able to help

**Comment by zakius** [comment]
honestly I have no idea what may be wrong, I just tried importing both old and new file (as I've added few extra properties to articles) and both worked just fine, would you mind clearing your extension data, uninstalling it and then installing and importing again?

or maybe I do have one idea, I removed the `unlimited_storage` permission in attempt to make CWS happy, maybe your bigger collection exceeds non-specified quota and gets damaged? could you check what happens if you add it to manifest?

**Comment by Lichtenshtein** [comment]
> or maybe I do have one idea, I removed the `unlimited_storage` permission in attempt to make CWS happy, maybe your bigger collection exceeds non-specified quota and gets damaged? could you check what happens if you add it to manifest?

That was the reason. Added the permission and that helped, import works again.

> I just tried it in chredge as I don't have any other chromium on this machine and it worked just fine

Strangly, it worked for me too: in Iron and on a new clean profile in Cent, but didn't want to work in my main profile no matter what i did. So i just replaced all files in 'extensions' folder with new ones (v2.3.1 → 2.4.0) except manifest, restartet the browser and updated extension that way.

P.S. When using a dark theme, by default the background of these elements is white, due to which the white text becomes unreadable.

![2020-2-21 18-19-47](https://user-images.githubusercontent.com/13855295/75061717-301c0300-54d9-11ea-9a6e-9797c916fd10.jpg)
![2020-2-21 18-20-35](https://user-images.githubusercontent.com/13855295/75061740-3c07c500-54d9-11ea-91c1-9070f42b8e5e.jpg)

Same is for options page.

![2020-2-21 18-19-472](https://user-images.githubusercontent.com/13855295/75061767-4cb83b00-54d9-11ea-847b-51ccd8d377b0.jpg)

Also some script refers to files inside the missing folder.

![2020-2-21 17-32-39](https://user-images.githubusercontent.com/13855295/75061662-14b0f800-54d9-11ea-91e4-f66aa3602db4.jpg)

P.P.S. 2.4.0 feels really good by the way, great job man

**Comment by zakius** [comment]
Okay, so I'll have to add that permission back

is your dark theme somehow enforced by browser? I'll take a look but whole style needs serious rework

I'm not sure why you are getting these weird paths, are you using `src` dir or `dist/chromium` generated by `grunt prepare`?

**Comment by Lichtenshtein** [comment]
> is your dark theme somehow enforced by browser?

Yes, i forgot about this..i have this enabled in browser flags:
chrome://flags/#enable-force-dark → Enabled with selective invertion of non-image elements

> are you using `src` dir or `dist/chromium` generated by `grunt prepare`?

No and no, i think

![123151611](https://user-images.githubusercontent.com/13855295/75071861-26e96100-54ee-11ea-9bc6-05593c758a67.jpg)

**Comment by zakius** [comment]
okay, there is issue with path of these files, I don't know how I never noticed this, thanks!

I don't think I can do anything about `selects`, it seems that dark mode is not ready to handle this element yet, I don't change colors of this element

I *can* force it to be visible, but there's no way of making it consistent with `inputs` without restyling also them completely

now I'll fix these images and dig a bit more to see if I can make it not-terrible for that dark mode
