### ISSUE TITLE
Add proper styling for media elements

### ISSUE THREAD

**Issue by zakius** [zakius/Smart-RSS#90]
Feature added in #81 needs proper presentation, possibly some icons representing content types too

**Comment by zakius** [comment]
@mostawesomedude and @atthegates 
I just added preview for images, audio and video files, it will display link as usual but clicking on the arrow on the left will display preview. Please note that it will only work for freshly loaded items as it relies on some data that wasn't loaded before.

I'm pushing updates to stores right now

**Comment by zakius** [comment]
Keeping this open in case someone has any comments, but I consider current solution good enough and will close it if none appear

**Comment by AtTheGates** [comment]
Thank you. Good solution. Perhaps an option to always expand/ display the preview would be nice. But if it's too complicated/ too much work or you doesn't want it in your extension, I could live with it.

This should be a bug: Preview images (after expanding) are cropped and there is no way to scroll down. And the text/ description is hidden:

![smart_cropped](https://user-images.githubusercontent.com/9346225/77256307-b7da6600-6c6d-11ea-9933-7f3d4425a064.png)

Feed address: https://backend.deviantart.com/rss.xml?q=+sort%3Atime+in%3Acustomization%2Fskins%2Fwindows%2Fwin10&type=deviation

Feed entry: https://www.deviantart.com/cleodesktop/art/Dark-Red-Alpha-Theme-Windows-10-1909-834712837

**Comment by zakius** [comment]
The solution I was able to find is less than ideal, causing multiple scrollbars to appear if both media element and contents are tall enough, I'll be playing with it a bit more to see if I find a better solution.

@ setting to always show preview: it is possible and easy to do, I'll add it in the next release

**Comment by zakius** [comment]
I still haven't got myself to add the setting, but scrolling should work properly in latest version

**Comment by AtTheGates** [comment]
Thank you very much. Works perfect now. Regarding the setting: Really no problem. :-)

**Comment by zakius** [comment]
Added in master, with ability to override global setting per source, will likely release sometime next week

**Comment by zakius** [comment]
I still have some issues with scrolling of content with images, if they take too long to load you can't scroll all the way down

**Comment by zakius** [comment]
just pushed new version to AMO, GitHub and Chrome Web Store on their way
