### ISSUE TITLE
2.8.1: disaster

### ISSUE THREAD

**Issue by gabri25ele** [zakius/Smart-RSS#93]
extension page blocked, firefox blocked. 
I have to close and reopen firefox. 
I can't enter into the addon page. 
How can downgrade to the previous version?

**Comment by gabri25ele** [comment]
the add is blocked when I open it
![sshot-1](https://user-images.githubusercontent.com/33927879/75761463-68bda700-5d39-11ea-8ba1-6d6c6fe774ad.png)

I have an old version (2.1.1), for now I back to that and it works again

**Comment by zakius** [comment]
I'll try looking into it but I'm using it with similar (even bigger) backlog and nothing like that happens

I assume that wring is the usual "page is slowing browser down" stuff?

**Comment by gabri25ele** [comment]
yes, "page is slowing browser down" and it remains indefinitely or almost.
impossible to use it like this.
I recovered 2.80 version and it works perfectly.

**Comment by zakius** [comment]
For me it works perfectly fine, from 2.8.0 to 2.8.1 there was only one change (forced sorting of articles) that indeed caused some minor slowdown on startup but it's far from that bad and I have even bigger backlog than you

Could you give it another try? And could you tell me what is your browser version?

In the meantime I'll seek another way of solving sorting issues

**Comment by zakius** [comment]
Okay, I cleaned up the comparator used to sort articles and added a new option to disable selection of `All Feeds` when you open the reader view, if the slowdown is as severe as in your case you should be able to get to options from `Extensions` panel, depending on your browser version the interface will vary, but the link is there for sure

New version is already available in Releases and should be accepted on AMO in a few hours, sorry for the trouble

**Comment by gabri25ele** [comment]
yes, probably there is a problem with sorting articles, beacause when I open the 2.81, I see all empty for a long, long, long, time.
I use Firefox 73.0.1
I try the new version as soon as possible.
(and yes, I would like to don't have "All feeds" selected by default at start)

**Comment by gabri25ele** [comment]
Installed **2.9.0**
everything is back to normal
😃

**Comment by zakius** [comment]
is startup bearable even with `All Feeds` autoselection or you changed it first?

**Comment by gabri25ele** [comment]
no, I ever had All Feeds automatically.
after update to 2.9, I unchecked it, but I didn't try with the 2.8.1 version.

**Comment by zakius** [comment]
okay, thanks for your help
