### ISSUE TITLE
Settings are not saved?

### ISSUE THREAD

**Issue by zakius** [zakius/Smart-RSS#97]

**Comment by zakius** [comment]
seems like they do save but aren't applied properly again

**Comment by rubel-22** [comment]
In all recent versions of Smart-RSS, interface settings after closing the browser, such as sorting and view, are not saved. Firefox 73.
The version of smart_rss_reader-2.0.4-fx that I downloaded 02/26/2019 works correctly.
File size-298kb

**Comment by rubel-22** [comment]
Download and install version from 03/12/2020 Smart-RSS-master.
Now the settings are saved except for the width of the column of news feeds.
